### ISSUE TITLE
请问如何删除统计错误的网站

### ISSUE THREAD

**Issue by kokojacket** [uxiaohan/HanAnalytics#1]
![Clip_2024-09-22_23-37-24](https://github.com/user-attachments/assets/3f424f05-948c-4202-ac6e-fa0e3b6625ce)
一开始没有修改data-website-id

**Comment by uxiaohan** [comment]
> ![Clip_2024-09-22_23-37-24](https://private-user-images.githubusercontent.com/74887370/369699123-3f424f05-948c-4202-ac6e-fa0e3b6625ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjc3NjgsIm5iZiI6MTcyNzA2NzQ2OCwicGF0aCI6Ii83NDg4NzM3MC8zNjk2OTkxMjMtM2Y0MjRmMDUtOTQ4Yy00MjAyLWFjNmUtZmEwZTNiNjYyNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA0NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OGE5MjI1NTE4N2Q1MzIyNDU5MWRhNTRkOWE0NWMyOGYxMmFlZjI1YTBmYzY4MjZiMWI0OWUwNzhkMTAwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nUwYjzyvP8rvEFtxNSVyYdMKOEqy8507eHU6e_14t6I) 一开始没有修改data-website-id


这个暂时无法删除，可以在 App.vue中的 getSiteList 函数中 过滤掉

```
  const res = await fetch('/api', { method: 'POST', headers: { 'Content-Type': 'application/json', }, body: JSON.stringify({ type: 'list' }) })
  const { data } = await res.json()
  siteList.value = data.filter((i: any) => i != '自定义网站唯一标识');
  siteValue.value = siteList.value[0]
  if (siteValue.value) getDatas()
```

**Comment by kokojacket** [comment]
是修改这部分代码吗：
![image](https://github.com/user-attachments/assets/d19e58eb-3467-4cc5-b518-aa6b161fa858)

**Comment by uxiaohan** [comment]
> 是修改这部分代码吗： ![image](https://private-user-images.githubusercontent.com/74887370/369756389-d19e58eb-3467-4cc5-b518-aa6b161fa858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjgzODcsIm5iZiI6MTcyNzA2ODA4NywicGF0aCI6Ii83NDg4NzM3MC8zNjk3NTYzODktZDE5ZTU4ZWItMzQ2Ny00Y2M1LWI1MTgtYWE2YjE2MWZhODU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA1MDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDc3YTdhMzQxZTFhOGI3ZTYzNTNlMWRhMTBiZTNmYmE2NDkyNzY2ZWIyZmViNWI0MjY0YTJkMGQ1NzNmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.usnQJKna6K1dgnW-4NIm6Pn1s3sS7z-yt4EP4S_PLgA)

是的，替换掉即可
